export const nameTranslations = [
  { lang: "English", name: "ILHAN HELAL" },
  { lang: "Arabic", name: "إلهان هلال" },
  { lang: "French", name: "ILHAN HELAL" },
  { lang: "Spanish", name: "ILHAN HELAL" },
  { lang: "German", name: "ILHAN HELAL" },
  { lang: "Chinese (Simplified)", name: "伊尔汗·赫拉尔" },
  { lang: "Chinese (Traditional)", name: "伊爾汗·赫拉爾" },
  { lang: "Japanese", name: "イルハン・ヘラル" },
  { lang: "Hindi", name: "इल्हान हेलाल" },
  { lang: "Russian", name: "ИЛЬХАН ХЕЛАЛ" },
  { lang: "Korean", name: "일한 헬랄" },
  { lang: "Greek", name: "ΙΛΧΑΝ ΧΕΛΑΛ" },
  { lang: "Thai", name: "อิลฮาน เฮลาล" },
  { lang: "Hebrew", name: "אילהאן הלאל" },
  { lang: "Bengali", name: "ইলহান হেলাল" },
  { lang: "Persian", name: "ایلهان هلال" },
  { lang: "Turkish", name: "İLHAN HELAL" },
  { lang: "Vietnamese", name: "ILHAN HELAL" },
  { lang: "Portuguese", name: "ILHAN HELAL" },
  { lang: "Italian", name: "ILHAN HELAL" },
  { lang: "Dutch", name: "ILHAN HELAL" },
  { lang: "Ukrainian", name: "ІЛЬХАН ХЕЛАЛ" },
  { lang: "Polish", name: "ILHAN HELAL" },
  { lang: "Romanian", name: "ILHAN HELAL" },
  { lang: "Czech", name: "ILHAN HELAL" },
  { lang: "Swedish", name: "ILHAN HELAL" },
  { lang: "Hungarian", name: "ILHAN HELAL" },
  { lang: "Tamil", name: "இல்ஹான் ஹெலால்" },
  { lang: "Telugu", name: "ఇల్హాన్ హెలాల్" },
  { lang: "Marathi", name: "इल्हान हेलाल" },
  { lang: "Gujarati", name: "ઇલ્હાન હેલાલ" },
  { lang: "Kannada", name: "ಇಲ್ಹಾನ್ ಹೆಲಾಲ್" },
  { lang: "Malayalam", name: "ഇൽഹാൻ ഹെലാൽ" },
  { lang: "Punjabi", name: "ਇਲਹਾਨ ਹੇਲਾਲ" },
  { lang: "Urdu", name: "الہان ہلال" },
  { lang: "Indonesian", name: "ILHAN HELAL" },
  { lang: "Malay", name: "ILHAN HELAL" },
  { lang: "Filipino", name: "ILHAN HELAL" },
  { lang: "Burmese", name: "အီလ်ဟန် ဟဲလာလ်" },
  { lang: "Khmer", name: "អ៊ីលហាន់ ហេឡាល់" },
  { lang: "Lao", name: "ອິລຮານ ເຮລາລ" },
  { lang: "Sinhala", name: "ඉල්හාන් හෙලාල්" },
  { lang: "Nepali", name: "इल्हान हेलाल" },
  { lang: "Amharic", name: "ኢልሃን ሄላል" },
  { lang: "Georgian", name: "ილჰან ჰელალ" },
  { lang: "Kazakh", name: "ІЛХАН ХЕЛАЛ" },
  { lang: "Uzbek", name: "ILXON HALOL" },
  { lang: "Mongolian", name: "ИЛХАН ХЭЛАЛ" },
];

// Color palette for consistent theming
export const themeColors = {
  primary: {
    cyan: '#06b6d4',
    purple: '#a855f7',
    indigo: '#6366f1',
  },
  accent: {
    green: '#10b981',
    pink: '#ec4899',
    blue: '#3b82f6',
  },
  gradients: {
    primary: 'linear-gradient(135deg, #06b6d4 0%, #6366f1 50%, #a855f7 100%)',
    secondary: 'linear-gradient(135deg, #10b981 0%, #06b6d4 100%)',
    accent: 'linear-gradient(135deg, #ec4899 0%, #a855f7 100%)',
  }
};
